### ISSUE TITLE
Implement backend functionality for fetching and displaying cocktail recipes.

### ISSUE THREAD

**Issue by azharanees** [azharanees/Mixology#5]
As a user, I will be able to **view the cocktail recipes fetched** **from the API**

**Comment by allstarcom** [comment]
Commit Link :  https://github.com/azharanees/Mixology/commit/acdd9e7f05fed5efd65c94be0d27c1a663e6439f
                         https://github.com/azharanees/Mixology/commit/1434ed033f9e478664d5b8ecdc7ba82a58c220d6
                         https://github.com/azharanees/Mixology/commit/8cdd02101e312e002e5498ef1ee6c68990d08237
